language: minimal
services:
- docker
before_install:
- './.travis/main.sh'
before_script:
- curl -sL https://git.io/tusk | bash -s -- -b .direnv/bin latest
script:
- "./.direnv/bin/tusk build --cmd docker"
- "./.direnv/bin/tusk push --cmd docker"
