---
version: "2.4"
services:
  base:
    image: mgnsk/toolbox-base:latest
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - uid
        - gid

  toolbox:
    image: mgnsk/toolbox:latest
    depends_on:
      - base
    build:
      context: .
      dockerfile: Dockerfile
    # cap_drop:
    # - ALL
    mem_limit: 2g
    volumes:
      - ".mount/code/merged:/code"
      - "tmp:/tmp"
      - "cache:/homedir/.cache"
      - "bash-history:/homedir/.bash_history"
      - "nvim-data:/homedir/.local/share/nvim"
      - "coc-clangd-data:/homedir/.config/coc/extensions/coc-clangd-data"
      - "coc-phpls-data:/homedir/.config/coc/extensions/coc-phpls-data"
      - "direnv-data:/homedir/.local/share/direnv"
      - "tmux-resurrect:/homedir/.tmux/resurrect"
      - "composer-global:/homedir/.composer"
      - "npm-global:/homedir/.npm-global"
      - "go-global:/homedir/go"
      - "python-global:/homedir/.local/lib/python3.8"
      - "cargo-data:/homedir/.cargo"
      - "local-bin:/homedir/.local/bin"
      - "usr-local-lib:/usr/local/lib"
    hostname: toolbox
    ports:
      # parcel
      - 1234
      - 5000
      - 33969

volumes:
  tmp:
  cache:
  bash-history:
  nvim-data:
  coc-clangd-data:
  coc-phpls-data:
  direnv-data:
  tmux-resurrect:
  composer-global:
  npm-global:
  go-global:
  python-global:
  cargo-data:
  local-bin:
  usr-local-lib:
