version: "2.4"
services:
  dev-env:
    image: mgnsk/dev-env:latest
    build:
      context: ./image
      args:
        - uid=${UID}
        - gid=${GID}
        - dot_url=${DOT_URL}
        - dot_commit=${DOT_COMMIT}
    cap_drop:
      - ALL
    mem_limit: 2g
    volumes:
      - "./mount:/mount"
      - "cache:/homedir/.cache"
      - "ssh-key:/homedir/.ssh"
      - "nvim-data:/homedir/.local/share/nvim"
      - "direnv-data:/homedir/.local/share/direnv"
      - "tmux-resurrect:/homedir/.tmux/resurrect"
    hostname: dev-env

  volumes:
    cache:
    ssh-key:
    nvim-data:
    direnv-data:
    tmux-resurrect:
