version: '2.4'
services:
  dev-env:
    image: mgnsk/dev-env:latest
    build:
      context: ./image
      args:
      - UID=3000
      - GID=3000
      - USER=user
      - GROUP=user
    cap_drop:
    - ALL
    mem_limit: 2g
    volumes:
    - "./mount:/mount"
    - "ssh-key:/homedir/.ssh"
    - "coc-data:/homedir/.config/coc"
    - "nvim-data:/homedir/.local/share/nvim"
    - "direnv-data:/homedir/.local/share/direnv"
    - "tmux-resurrect:/homedir/.tmux/resurrect"
    hostname: dev-env

  volumes:
    ssh-key:
    coc-data:
    nvim-data:
    direnv-data:
    tmux-resurrect:
