version: "2.4"
services:
  dev-env:
    image: mgnsk/dev-env:latest
    build:
      context: ./image
      args:
        - uid=${UID}
        - gid=${GID}
        - dot_url=${DOT_URL}
        - dot_commit=${DOT_COMMIT}
    cap_drop:
      - ALL
    mem_limit: 2g
    volumes:
      - "./mount:/mount"
      - "ssh-key:/homedir/.ssh"
      - "cache:/homedir/.cache"
      - "nvim-data:/homedir/.local/share/nvim"
      - "coc-clangd-data:/homedir/.config/coc/extensions/coc-clangd-data"
      - "coc-phpls-data:/homedir/.config/coc/extensions/coc-phpls-data"
      - "direnv-data:/homedir/.local/share/direnv"
      - "tmux-resurrect:/homedir/.tmux/resurrect"
      - "composer-global:/homedir/.composer"
      - "npm-global:/homedir/.npm-global"
      - "go-global:/homedir/go"
    hostname: dev-env

  volumes:
    ssh-key:
    cache:
    nvim-data:
    coc-clangd-data:
    coc-phpls-data:
    direnv-data:
    tmux-resurrect:
    composer-global:
    npm-global:
    go-global:
