version: '2'

volumes:
  ssh-key:
  coc-data:

services:
  dev-env:
    image: mgnsk/dev-env:latest
    hostname: dev-env
    environment:
    - UID=${UID}
    - USER=${USER}
    - GID=${GID}
    - GROUP=${GROUP}
    working_dir: /code
    volumes:
    - ssh-key:/homedir/.ssh
    - coc-data:/homedir/.config/coc
    - ./code:/code

