version: "2.4"
services:
  dev-env:
    image: mgnsk/dev-env:latest
    build:
      context: ./image
      args:
        - uid
        - gid
        - dot_url
        - dot_commit
    cap_drop:
      - ALL
    mem_limit: 2g
    volumes:
      - "./mount:/mount"
      - "ssh-key:/homedir/.ssh"
      - "cache:/homedir/.cache"
      - "nvim-data:/homedir/.local/share/nvim"
      - "coc-clangd-data:/homedir/.config/coc/extensions/coc-clangd-data"
      - "coc-phpls-data:/homedir/.config/coc/extensions/coc-phpls-data"
      - "direnv-data:/homedir/.local/share/direnv"
      - "tmux-resurrect:/homedir/.tmux/resurrect"
      - "composer-global:/homedir/.composer"
      - "npm-global:/homedir/.npm-global"
      - "go-global:/homedir/go"
      - "python-global:/homedir/.local/lib/python3.8"
      - "local-bin:/homedir/.local/bin"
    hostname: dev-env

  volumes:
    ssh-key:
    cache:
    nvim-data:
    coc-clangd-data:
    coc-phpls-data:
    direnv-data:
    tmux-resurrect:
    composer-global:
    npm-global:
    go-global:
    python-global:
    local-bin:
