version: "2.4"

services:
  dev-env:
    image: dev-env:sandbox
    hostname: dev-env
    # Use full resources for earlyoom to work correctly.
    #cpus: 2.0
    #mem_limit: 2G
    #mem_reservation: 1G
    #memswap_limit: 4G
    #mem_swappiness: 0
    build:
      context: ./image
      target: dev-env
      args:
      - user
      - dot_commit
    volumes:
    - ./code:/home/${USER}/code

