version: "2.4"

services:
  dev-env:
    image: mgnsk/dev-env
    hostname: dev-env
    # Use full resources for earlyoom to work correctly.
    #cpus: 2.0
    #mem_limit: 2G
    #mem_reservation: 1G
    #memswap_limit: 4G
    #mem_swappiness: 0
    build:
      context: ./image
      target: dev-env
      args:
      - dot_url
      - dot_commit
    ports:
      - 6060:6060 # gopls debug
    volumes:
      - ./code:/code

