version: "2.4"

volumes:
  goproxy-cache:
  gopath:
  nvim:

services:
  dev-env:
    image: dev-env:sandbox
    hostname: dev-env
    # Use full resources for earlyoom to work correctly.
    #cpus: 2.0
    #mem_limit: 2G
    #mem_reservation: 1G
    #memswap_limit: 4G
    #mem_swappiness: 0
    build:
      context: ./image
      target: dev-env
      args:
      - user
      - dot_commit
    volumes:
    - ./code:/home/${USER}/code
    - gopath:/home/${USER}/go
    - nvim:/home/${USER}/.config/nvim
    environment:
    - GOPROXY=http://goproxy:8081
    ports:
    - 6060:6060 # gopls debug
    depends_on:
    - goproxy

  goproxy:
    image: goproxy/goproxy:latest
    volumes:
    - goproxy-cache:/go

