name: dev-env
on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v2
        run: >
          sh setup.sh

          ./.direnv/tusk build

          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{
          secrets.DOCKER_USERNAME }} --password-stdin

          docker push mgnsk/dev-env:latest
