name: dev-env
on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install tusk
        run: |
          curl -sL https://git.io/tusk | bash -s -- -b .direnv/bin latest

      - name: Build
        run: |
          ./.direnv/bin/tusk build

      - name: Push
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login --username mgnsk --password-stdin
          docker push mgnsk/dev-env:latest

