FROM alpine:edge AS build-base

RUN apk update \
	&& apk --no-cache upgrade \
	&& apk --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing add \
	coreutils \
	bash \
	sudo \
	shadow \
	&& echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers


# Development image.
FROM build-base AS dev-env

ARG UID
ARG GID
ARG USER
ARG GROUP

RUN addgroup -g ${GID} ${GROUP} \
	&& groupmod -g ${GID} ${GROUP} \
	&& adduser \
	--disabled-password \
	--gecos "" \
	--home /homedir \
	--ingroup ${GROUP} \
	--uid ${UID} \
	${USER} \
	&& addgroup ${USER} wheel

VOLUME /code

WORKDIR /code

USER user
